name: Add New Project to Portfolio

on:
  workflow_dispatch:
    inputs:
      repo_url:
        description: 'Full URL of the new GitHub repository (e.g., https://github.com/your-user/your-repo)'
        required: true
      image_path:
        description: 'Path to the project image (e.g., assets/img/portfolio/new-project.png)'
        required: true
        default: 'assets/img/portfolio/default.png'

jobs:
  add-project:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Fetch repo details and update data file
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO_URL: ${{ github.event.inputs.repo_url }}
          IMAGE_PATH: ${{ github.event.inputs.image_path }}
        run: |
          repo_details=$(gh repo view $REPO_URL --json name,description,url,repositoryTopics)

          if [ -z "$repo_details" ]; then
            echo "::error::Could not fetch repository details. Check if the URL is correct and the repository is public."
            exit 1
          fi

          echo "Successfully fetched details for: $(echo $repo_details | jq -r .name)"

          # This 'jq' command is now updated to handle null topics
          new_entry=$(echo "$repo_details" | jq -r --arg image_path "$IMAGE_PATH" '
            (
              "- name: \"\(.name)\"\n" +
              "  image: \"\($image_path)\"\n" +
              "  description: \"\(.description // "No description provided.")\"\n" +
              "  tech: \((.repositoryTopics // []) | map(.topic.name) | tojson)\n" + # <-- THIS IS THE LINE THAT WAS FIXED
              "  github_url: \"\(.url)\"\n" +
              "  demo_url: \"\""
            )
          ')

          echo -e "\n${new_entry}" >> _data/projects.yml
          echo "Updated _data/projects.yml with the new project."

      - name: Commit and push if files changed
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "feat: Add ${{ github.event.inputs.repo_url }} to portfolio"
          file_pattern: _data/projects.yml
          commit_user_name: "GitHub Actions Bot"
          commit_user_email: "github-actions@github.com"